final products = [
  {
    "id": 1,
    "name": "Men's Nike Shoe",
    "price": 20.50,
    "sizes": [8, 9, 10, 12],
    "imageUrl": 'images/img1.png',
    "company": "Nike",
  },
  {
    "id": 2,
    "name": "Women's Adidas Sneaker",
    "price": 25.75,
    "sizes": [8, 9, 10, 12],
    "imageUrl": 'images/img2.png',
    "company": "Adidas",
  },
  {
    "id": 3,
    "name": "Kid's Puma Running Shoe",
    "price": 15.99,
    "sizes": [8, 9, 10, 12],
    "imageUrl": 'images/img3.png',
    "company": "Puma",
  },
  {
    "id": 4,
    "name": "Men's Reebok Training Shoe",
    "price": 22.99,
    "sizes": [8, 9, 10, 12],
    "imageUrl": 'images/img4.png',
    "company": "Reebok",
  },
  {
    "id": 5,
    "name": "Women's Walking Shoe",
    "price": 30.00,
    "sizes": [8, 9, 10, 12],
    "imageUrl": 'images/img5.png',
    "company": "New Balance",
  },
  {
    "id": 6,
    "name": "Kid's Sneaker",
    "price": 18.50,
    "sizes": [8, 9, 10, 12],
    "imageUrl": 'images/img6.png',
    "company": "Converse",
  },
];
